### ISSUE TITLE
save_fasta does not maintain ASV annotation

### ISSUE THREAD

**Issue by vfonti** [DanielSprockett/reltools#6]
Hello!
I am trying to convert a refseq element in my phyloseq object into a fasta file. I would like the sequences to be called by their ASV# indexes but I keep getting an error. The `save_fasta` function does not accept `rank= NULL`.
Here my pieces of code:

```
refseq(ps)
```
![RefSeq](https://user-images.githubusercontent.com/9551014/133773050-21513a7e-2528-4093-9d3d-939afe4fc6d0.png)
```
library(reltools)
save_fasta(ps, file = "path_to_my_folder/ps.fasta", rank = NULL)
> Error in if (is.null(rank) | !rank %in% rank_names(ps)) { : 
  argument is of length zero

```
What's wrong? 
Thanks to anyone who would like to help.

**Comment by DanielSprockett** [comment]
Have you tried using `rank  = "ASV"` ?

What is the output of `rank_names(ps)` ?

**Comment by vfonti** [comment]
Hi! 
Thank you very much for replying!
The rank names of my phyloseq object are the classics:  "Kingdom", "Phylum" , "Class" ,  "Order" ,  "Family", "Genus". 

I have just tried with` rank = "ASV"`. The command does work but it does not use the ASV indexes in refseq. What I got it's a fasta file with sequences named sequentially. Indeed, the command gives this message back: 
`> Rank not found. Naming sequences sequentially (i.e. ASV_#).`

**Comment by DanielSprockett** [comment]
Right, so it looks like you don't have a column in your `tax_table()` named "ASV", I'm guessing you just have the `taxa_names()` given arbitrary ASV names. This function won't work for what you want it to, but you can try pulling this bit of code from it:

First:
```
file = "path_to_my_folder/ps.fasta"
seqs <- as.vector(refseq(ps))
seq_names <- taxa_names(ps)
```

Then:

```
 for (i in 1:ntaxa(ps)) {
        cat(paste(">", seq_names[i], sep = ""), file = file, 
            sep = "\n", append = TRUE)
        cat(seqs[i], file = file, sep = "\n", append = TRUE)
}
```

**Comment by vfonti** [comment]
Thanks @DanielSprockett !
That did the trick perfectly!!
